# Generated by Django 3.0.8 on 2020-07-12 03:16

from django.db import migrations

# read this link for more information on data migrations (the way I populated the database)
# https://docs.djangoproject.com/en/3.0/topics/migrations/#data-migrations

from enum import Enum
	
def insertSize(apps, schema_editor):
	"""Populate the Size model table"""
	Size = apps.get_model('pizzeria', 'Size')
	sizes = (
		Size(name='personal', price=10),
		Size(name='mediana', price=16),
		Size(name='familiar', price=20)
	)
	Size.objects.bulk_create(sizes)

def insertTopping(apps, schema_editor):
	"""Populate the Topping model table"""
	Topping = apps.get_model('pizzeria', 'Topping')
	toppings = (
		Topping(name='jamón', price=4.0),
		Topping(name='champiñones', price=3.5),
		Topping(name='pimentón', price=3.0),
		Topping(name='doble queso', price=4.0),
		Topping(name='aceitunas', price=5.75),
		Topping(name='pepperoni', price=3.85),
		Topping(name='salchichón', price=6.25),
	)
	Topping.objects.bulk_create(toppings)
		
class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
		migrations.RunPython(insertSize),
		migrations.RunPython(insertTopping)
    ]
